name: "Test"

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              working-directory: ./Q
              run: npm ci

            - name: Run Jest Tests
              working-directory: ./Q
              run: npm test

    integration_tests_8:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              working-directory: ./Q
              run: npm ci

            - name: Build
              working-directory: ./Q
              run: make

            - name: Run Integration Tests
              working-directory: ./Q
              run: npm test integration
